name: test
on:
  push:
permissions:
  actions: read
  checks: read
  contents: read
  id-token: write
  pull-requests: write
jobs:
  build-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Print environment variable
        run: echo ${{ vars.ENV }}

  build-uat:
    runs-on: ubuntu-latest
    environment: uat
    steps:
      - name: Print environment variable
        run: echo ${{ vars.ENV }}
